### ISSUE TITLE
Long pressing to launch the colour picker results in an event firing on the picker popup

### ISSUE THREAD

**Issue by sumnerboy12** [austinscreations/OXRS-AC-TP32-ESP-FW#36]
Depending on where the original tile is positioned when you press+hold to launch the popup, after the popup launches and your finger is still touching the screen, it causes an event to fire on the picker popup.

Could we somehow ignore events on the popup until after the user releases their finger from launching the popup?

Hope that makes sense.

**Comment by austinscreations** [comment]
the old one does that on screen wakeup too if im not mistaken
