### ISSUE TITLE
Auto-close dropdown selector if nothing selected after 60s

### ISSUE THREAD

**Issue by sumnerboy12** [austinscreations/OXRS-AC-TP32-ESP-FW#8]
Probably just use the same `noActivitySecondsToHome` config for the timeout?

Same with the new selector thing you added as well?

**Comment by moinmoin-sh** [comment]
> Same with the new selector thing you added as well?

the selector thing is displayed on-tile only and disappears after 2 sec of inactivity of the up/down buttons. Same behavior as the level bar indicator

**Comment by moinmoin-sh** [comment]
This should include the `remote `popup and the `colorPicher `popups as well.

**Comment by sumnerboy12** [comment]
One popup that **shouldn't** auto-close is a `keyPadBlocking` tile - which it currently does. If I launch a `keyPadBlocking` tile on a non-home screen, I am unable to close it (as expected), but after 60s the panel reverts to the home screen. Navigating back to the screen with the `keyPadBlocking` tile correctly shows the blocking key pad, but I don't think it should revert to the home screen in this scenario.

**Comment by moinmoin-sh** [comment]
Kind of overlap here. I had the auto close ready since a few days but didn't merge - wanted to get the colorPicker done first. When testing the function today I ran into the issues that you describe above and fixed it, None of the keypads is auto closed.  I pushed the PR before I read your post.
